(** * Extraction to OCaml

    Extracts the verified state machine to OCaml for use as a native
    runtime checker. *)

Require Import Generated.

(** Extraction: produce OCaml module [Forge_state_machine].
    The extracted code is used by [checker.ml] (also generated by gen_coq.rs)
    to perform runtime verification of the skill loop invariants. *)

From Stdlib Require Import ExtrOcamlBasic ExtrOcamlString ExtrOcamlNatInt.

Extraction Language Ocaml.

Extraction "extraction/forge_state_machine.ml"
  State all_states entry_points terminal_states is_terminal successors rank
  Transition Reachable Path max_iterations.
