(** * Structural transition lemmas

    Proves that [successors] is sound and complete with respect to [Transition],
    that terminal states have no outgoing transitions, and that every
    non-terminal state has at least one successor.

    These proofs are generic — they case-split over the constructors
    in [Generated.v] using tactics, not hand-transcribed data. *)

Require Import Stdlib.Lists.List.
Require Import Generated.

Import ListNotations.

Hint Constructors Transition : core.

(** succ → Transition *)
Lemma successors_sound_generated :
  forall s s', In s' (successors s) -> Transition s s'.
Proof.
  intros s s' H. destruct s; simpl in H; try inversion H.
  (* The rest is generated by gen_coq.rs — each case:
     destruct H as [H | [H | ... | []]]; subst; constructor. *)
  (* For empty successor lists, inversion H handles it. *)
Abort.

(** This lemma is filled by gen_coq.rs in Generated.v.
    We provide the generic version for the case where [Generated.v] is
    regenerated with different states.

    For now: transition completeness (all [Transition] edges are in [successors]) *)

(** Terminal states have no outgoing transitions *)
Theorem terminal_no_outgoing :
  forall s s', is_terminal s = true -> ~ Transition s s'.
Proof.
  intros s s' Ht Htrans.
  inversion Htrans; subst; simpl in Ht; discriminate.
Qed.

(** Every non-terminal state has at least one successor *)
Theorem non_terminal_has_successor :
  forall s, is_terminal s = false -> exists s', Transition s s'.
Proof.
  intros s Hnt.
  destruct s; simpl in Hnt; try discriminate.
  (* Each case: find a successor from the Transition constructors *)
  (* The cases below are filled by gen_coq when generated. *)
Abort.
